### ISSUE TITLE
Failed to install generator-ng2-seed-advanced

### ISSUE THREAD

**Issue by ChinaShrimp** [peoplewareDo/generator-ng2-seed-advanced#7]
For installing `generator-ng2-seed-advanced`, additiona gulp packages are requied:
```
npm install -g gulp gulp-cli
```

Suggest to add above to installation steps, otherwise the installation will fail. Thanks!

**Comment by ChinaShrimp** [comment]
After installing gulp dependencies, I also got following errors. Are there any steps missing? Thank you.

```
[10:32:00] Failed to load external module ts-node/register
[10:32:00] Failed to load external module typescript-node/register
[10:32:00] Failed to load external module typescript-register
[10:32:00] Failed to load external module typescript-require
/Users/lyon/.nvm/versions/node/v6.9.4/lib/node_modules/generator-ng2-seed-advanced/node_modules/angular2-seed-advanced/gulpfile.ts:1
(function (exports, require, module, __filename, __dirname) { import * as gulp from 'gulp';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/Users/lyon/.nvm/versions/node/v6.9.4/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/lyon/.nvm/versions/node/v6.9.4/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
/Users/lyon/.nvm/versions/node/v6.9.4/lib
└── (empty)

npm WARN @ngrx/core@1.2.0 requires a peer of rxjs@^5.0.0-beta.12 but none was installed.
npm WARN @ngrx/store@2.2.1 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN @ngrx/store@2.2.1 requires a peer of rxjs@^5.0.0-beta.12 but none was installed.
npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/lyon/.nvm/versions/node/v6.9.4/bin/node" "/Users/lyon/.nvm/versions/node/v6.9.4/bin/npm" "install" "-g" "generator-ng2-seed-advanced"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! angular2-seed-advanced@1.0.0 postinstall: `typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed-advanced@1.0.0 postinstall script 'typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed-advanced package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed-advanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed-advanced
npm ERR! There is likely additional logging output above.
```

**Comment by victorsosa** [comment]
thanks the documentation will be updated with this

**Comment by victorsosa** [comment]
fixed

**Comment by SanthoshMR** [comment]
Hi, I still see this error when I try to install (even after installing all the global dependencies):

(function (exports, require, module, __filename, __dirname) { import * as gulp from 'gulp';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
.....
.....

Am I missing anything?
